# Generated by Django 4.2.4 on 2023-09-08 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFertilizante',
            fields=[
                ('RegistroICA', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=50)),
                ('Frecuencia', models.CharField(max_length=50)),
                ('ValorProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FechaUltimaAplicacion', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControlHongo',
            fields=[
                ('RegistroICA', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=50)),
                ('Frecuencia', models.CharField(max_length=50)),
                ('ValorProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PeriodoCarencia', models.IntegerField()),
                ('NombreHongo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControlPlaga',
            fields=[
                ('RegistroICA', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=50)),
                ('Frecuencia', models.CharField(max_length=50)),
                ('ValorProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PeriodoCarencia', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('NumCatastro', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('Municipio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('Documento', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('Codigo', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('TipoDeCultivo', models.CharField(max_length=100)),
                ('Finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Viveros', to='vivero_app.finca')),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now=True)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Vivero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Labores', to='vivero_app.vivero')),
            ],
        ),
        migrations.AddField(
            model_name='finca',
            name='Productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fincas', to='vivero_app.productor'),
        ),
    ]
